name: .NET Release

# 触发器配置
on:
  push:
    # 触发分支
    branches: [ "main" ]
    tags: [ 'v*' ]

jobs:
  # 编译任务
  build:
    # 使用矩阵策略，为多个平台并行编译
    strategy:
      matrix:
        # 定义不同平台的配置
        include:
          - rid: win-x64
            os: windows-latest
          - rid: win-arm64
            os: windows-latest
          - rid: linux-x64
            os: ubuntu-latest
          - rid: linux-arm64
            os: ubuntu-latest
          - rid: osx-x64
            os: macos-latest
          - rid: osx-arm64
            os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore AYLink/AYLink.csproj

      - name: Build and publish
        run: dotnet publish AYLink/AYLink.csproj -c Release -r ${{ matrix.rid }} -o ./publish_output

      - name: Archive production artifacts (Windows)
        if: runner.os == 'Windows'
        run: Compress-Archive -Path ./publish_output/* -DestinationPath AYLink-${{ matrix.rid }}.zip

      - name: Archive production artifacts (Linux & macOS)
        if: runner.os != 'Windows'
        run: tar -czvf AYLink-${{ matrix.rid }}.tar.gz -C ./publish_output .

      - name: Upload artifact for release
        uses: actions/upload-artifact@v4
        with:
          name: release-asset-${{ matrix.rid }}
          path: AYLink-${{ matrix.rid }}.* # 使用通配符匹配 .zip 和 .tar.gz
          retention-days: 1

  # 发布任务
  release:
    # 只有在 build 任务成功后才运行
    needs: build
    # 只有当触发事件是推送 tag 时才运行
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write # 需要写入权限来创建 Release
      
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/*/*.*"
          # 使用 Git 标签作为 Release 的名称
          tag: ${{ github.ref_name }}
          # 自动生成 Release notes
          generateReleaseNotes: true